project_id = "rmxqigouctwqkpwiapbu"

[functions.parse-invoice]
verify_jwt = false

[functions.migrate-installments]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.add-member]
verify_jwt = false

[functions.pluggy-connect]
verify_jwt = false

[functions.pluggy-webhook]
verify_jwt = false
